stages:
  - deploy

helm-deploy:
  stage: deploy
  tags:
    - k8s-runner-amd64
  image:
    name: alpine/helm:latest
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --atomic --create-namespace --namespace=monitoring
